### ISSUE TITLE
Rated custom games

### ISSUE THREAD

**Issue by Matttaylor8910** [Matttaylor8910/generals-enhancements#11]
From hun on discord:
> suggestion: rated custom games.
It should be good that you can pick a box that you want rated games. And if you play custom 2v2, this counts in 2v2 leaderboard. (And you get stars in custom 1v1, etc.)

This would require server work unless we decided to have our own rating system alongside the stars

**Comment by Lazerpent** [comment]
This will never happen because it would give players the ability to boost themselves using two accounts. 

If anything with rated customs was to happen, it would be #14
